---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: reviews
  namespace: reviews
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  selector:
    matchLabels:
      name: reviews
  template:
    metadata:
      labels:
        name: "reviews"
    spec:
      containers:
      - name: reviews
        image: index.docker.io/ambrosiaaaaa/my-reviews-image:{{image-tag}}
        imagePullPolicy: Always
        env:
        - name: RATINGS_HOSTNAME
          value: ratings
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: reviews
  namespace: reviews
spec:
  ports:
  - name: "reviews"
    port: 9080
    targetPort: 9080
  selector:
    name: reviews
